### ISSUE TITLE
Feature request: Retrieve user from token

### ISSUE THREAD

**Issue by ikasoba** [yitsushi/go-misskey#101]
**Is your feature request related to a problem? Please describe.**
I am trying to build a client for misskey in golang.
I was looking for a library for misskey and found this great library and decided to use it. However, it seems that there is no function (like `/api/i`) to get a user from a token.
Sorry if I just don't know it.

**Describe the solution you'd like**
I would like to add the ability to retrieve the user assigned to a token.

I've written a [Pull Request](https://github.com/yitsushi/go-misskey/pull/100) to resolve this issue, and I'd like you to Merge it if this is not a problem.

**Describe alternatives you've considered**

**Additional context**

**Comment by yitsushi** [comment]
Resolved by https://github.com/yitsushi/go-misskey/pull/100
