### ISSUE TITLE
Implement Messaging

### ISSUE THREAD

**Issue by yitsushi** [yitsushi/go-misskey#13]
- [ ] messaging/history
 - [ ] messaging/messages
 - [ ] messaging/messages/create
 - [ ] messaging/messages/delete
 - [ ] messaging/messages/read

https://misskey.io/api-doc#tag/messaging

**Comment by twocs** [comment]
@yitsushi The messaging endpoints are gone now. I think you can close this card as "wont-do".
https://github.com/misskey-dev/misskey/discussions/12157
